import numpy as np

LEFT = 0
DOWN = 1
RIGHT = 2
UP = 3

EPSILON = 0.1
GAMMA = 0.90
LEARNING_RATE = 0.1
MAX_STEPS = np.inf
NUMBER_OF_EPISODES = 2000

MAPS = {
    "4x4": ["SFFF", "FHFH", "FFFH", "HFFG"],
    "10x10": ["SFFFHFHFFF", "FHFFHHFFHF", "FFFHFFHFFF", "FFFFFFFFFF", "FFFFFFFFFH", 
    "HFFFFHHFFF", "FFFFHHHFFF", "FFFFFFHHHH", "HHFFFFHFFF", "HHHFFFFFFG"] 

    # "10x10": ["SFFFFFFFFF", "FHFHHFHFFF", "FFFFFHHFHF", "HFFFFFFFHH", "FFFHFHFFFF", "FFFFFHHFHF", "FHFFFHHFFF", "FFHFFFHFHF", "FFHHFHFFFF", "FFFFFFFFFG"]
}

GRID_SIZE = 4